// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(props) {
  return React.createElement("div", undefined, "Hello webpack");
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
