// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var $$Window = {};

function App(props) {
  return React.createElement("canvas", undefined);
}

var make = App;

export {
  $$Window ,
  make ,
}
/* react Not a pure module */
