// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as PixiJs from "pixi.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as Client from "react-dom/client";

import './main.css'
;

var CanvasNotFound = /* @__PURE__ */Caml_exceptions.create("Index.CanvasNotFound");

var BodyNotFound = /* @__PURE__ */Caml_exceptions.create("Index.BodyNotFound");

function make(fill, position, x, y, linestyle, radius, param) {
  var g = new PixiJs.Graphics();
  if (fill !== undefined) {
    g.beginFill(fill);
  }
  var match;
  if (position !== undefined) {
    var position$1 = Caml_option.valFromOption(position);
    match = [
      position$1.x,
      position$1.y
    ];
  } else {
    match = [
      Js_option.getWithDefault(0.0, x),
      Js_option.getWithDefault(0.0, y)
    ];
  }
  if (linestyle !== undefined) {
    g.lineStyle(Caml_option.valFromOption(linestyle));
  }
  g.drawCircle(match[0], match[1], radius);
  g.endFill();
  return g;
}

var Circle = {
  make: make
};

var Shape = {
  Circle: Circle
};

window.onload = (function (param) {
    var body = document.querySelector("body");
    if (body == null) {
      throw {
            RE_EXN_ID: BodyNotFound,
            Error: new Error()
          };
    }
    var options = {
      backgroundColor: "white"
    };
    var app = new PixiJs.Application(options);
    var view = app.view;
    body.appendChild(view);
    ((async function (param) {
            var container = new PixiJs.Container();
            app.stage.addChild(container);
            var texture = await PixiJs.Assets.load("assets/bunny2.png");
            var bunny = new PixiJs.Sprite(texture);
            container.addChild(bunny);
            var numerals = await PixiJs.Assets.load("assets/numerals.png");
            var numerals$1 = new PixiJs.Sprite(numerals);
            numerals$1.tint = 12156969;
            container.addChild(numerals$1);
            bunny.eventMode = "static";
            var renderer = app.renderer;
            bunny.onclick = (function ($$event) {
                console.log($$event);
                app.stage.removeChild(container);
                container.destroy(undefined);
                var container$1 = new PixiJs.Container();
                var h = renderer.width;
                var w = renderer.height;
                var x = h * 0.75;
                var y = w / 2.0;
                var radius = 0.10 * Math.min(h, w);
                var graphics = make("yellow", undefined, x, y, {
                      width: 8,
                      color: "black"
                    }, radius, undefined);
                app.stage.addChild(container$1);
                container$1.addChild(graphics);
              });
            bunny.x = renderer.width / 2.0;
            numerals$1.x = renderer.width / 2.0;
            numerals$1.y = renderer.width / 2.0;
            var elapsed = {
              contents: 0.0
            };
            app.ticker.add(function (delta) {
                  elapsed.contents = elapsed.contents + delta;
                  bunny.x = 100.0 + Math.cos(elapsed.contents / 50.0) * 100.0;
                });
          })(undefined));
  });

var e = document.querySelector("#root");

if (e == null) {
  console.log("not found");
} else {
  Client.createRoot(e).render(React.createElement(App.make, {}));
}

export {
  CanvasNotFound ,
  BodyNotFound ,
  Shape ,
}
/*  Not a pure module */
