// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as PixiJs from "pixi.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";
import * as Client from "react-dom/client";

import './main.css'
;

var CanvasNotFound = /* @__PURE__ */Caml_exceptions.create("Index.CanvasNotFound");

var BodyNotFound = /* @__PURE__ */Caml_exceptions.create("Index.BodyNotFound");

window.onload = (function (param) {
    var body = document.querySelector("body");
    if (body == null) {
      throw {
            RE_EXN_ID: BodyNotFound,
            Error: new Error()
          };
    }
    var app = new PixiJs.Application();
    var view = app.view;
    body.appendChild(view);
    ((async function (param) {
            var texture = await PixiJs.Assets.load("assets/bunny.png");
            var bunny = new PixiJs.Sprite(texture);
            app.stage.addChild(bunny);
            var renderer = app.renderer;
            bunny.x = renderer.width / 2.0;
            var elapsed = {
              contents: 0.0
            };
            app.ticker.add(function (delta) {
                  elapsed.contents = elapsed.contents + delta;
                  bunny.x = 100.0 + Math.cos(elapsed.contents / 50.0) * 100.0;
                });
          })(undefined));
  });

var e = document.querySelector("#root");

if (e == null) {
  console.log("not found");
} else {
  Client.createRoot(e).render(React.createElement(App.make, {}));
}

export {
  CanvasNotFound ,
  BodyNotFound ,
}
/*  Not a pure module */
