// Generated by ReScript, PLEASE EDIT WITH CARE


var View = {};

var Point = {};

function Make(R) {
  return {};
}

var Rectangle = {};

var Path = {
  Make: Make,
  Rectangle: Rectangle
};

export {
  View ,
  Point ,
  Path ,
}
/* No side effect */
