// Generated by ReScript, PLEASE EDIT WITH CARE


var NamedColor = {};

var $$HTMLElement = {};

var FederatedPointerEvent = {};

var EventMode = {};

var DestroyOptions = {};

function Make(R) {
  return {};
}

var DisplayObject = {
  DestroyOptions: DestroyOptions,
  Make: Make
};

function Make$1(R) {
  return {};
}

var Tintable = {
  Make: Make$1
};

function Make$2(R) {
  return {};
}

var Positionable = {
  Make: Make$2
};

var Canvas = {};

function Make$3(R) {
  return {};
}

var Rectangle = {
  Make: Make$3
};

var Ticker = {};

function Make$4(R) {
  return {};
}

var Container = {
  Make: Make$4
};

var LineStyle = {};

var Graphics = {
  LineStyle: LineStyle
};

var CanvasRenderer = {};

var Texture = {};

var Point = {};

var Anchor = {};

var Sprite = {};

var Assets = {};

var Options = {};

var Application = {
  Options: Options
};

export {
  NamedColor ,
  $$HTMLElement ,
  FederatedPointerEvent ,
  EventMode ,
  DisplayObject ,
  Tintable ,
  Positionable ,
  Canvas ,
  Rectangle ,
  Ticker ,
  Container ,
  Graphics ,
  CanvasRenderer ,
  Texture ,
  Point ,
  Anchor ,
  Sprite ,
  Assets ,
  Application ,
}
/* No side effect */
