// Generated by ReScript, PLEASE EDIT WITH CARE


var FederatedPointerEvent = {};

var EventMode = {};

function Make(R) {
  return {};
}

var DisplayObject = {
  Make: Make
};

function Make$1(R) {
  return {};
}

var Tintable = {
  Make: Make$1
};

function Make$2(R) {
  return {};
}

var Positionable = {
  Make: Make$2
};

var View = {};

function Make$3(R) {
  return {};
}

var Rectangle = {
  Make: Make$3
};

var Ticker = {};

var Container = {};

var Renderer = {};

var Texture = {};

var Point = {};

var Anchor = {};

var Sprite = {};

var Assets = {};

var Options = {};

var Application = {
  Options: Options
};

export {
  FederatedPointerEvent ,
  EventMode ,
  DisplayObject ,
  Tintable ,
  Positionable ,
  View ,
  Rectangle ,
  Ticker ,
  Container ,
  Renderer ,
  Texture ,
  Point ,
  Anchor ,
  Sprite ,
  Assets ,
  Application ,
}
/* No side effect */
