// Generated by ReScript, PLEASE EDIT WITH CARE


var View = {};

function Make(R) {
  return {};
}

var Rectangle = {
  Make: Make
};

var Ticker = {};

var Renderer = {};

var Texture = {};

var Point = {};

var Anchor = {};

var Sprite = {};

var Assets = {};

var Stage = {};

var Application = {};

export {
  View ,
  Rectangle ,
  Ticker ,
  Renderer ,
  Texture ,
  Point ,
  Anchor ,
  Sprite ,
  Assets ,
  Stage ,
  Application ,
}
/* No side effect */
